site_name: RAG Pipeline for AI Agents
site_url: ""  # Empty for relative URLs
use_directory_urls: false  # Important for portability
theme:
  name: material
  logo: images/logo.png
  favicon: images/favicon.png
  font: 
    text: Adobe Clean
    code: Roboto Mono
  features:
    - navigation.sections
    - navigation.expand
    - navigation.tracking
    - navigation.paths
    - toc.integrate
    - search.highlight
    - search.suggest
    - search.share
    - content.code.annotate
    - content.code.copy  
    - permalink:true
  custom_dir: docs/overrides
  # Add CSS and JS customization
  extra_css:
    - css/extra.css
  extra_javascript:
    - js/extra.js
    - js/animations.js
  include:
    - readme.md

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

# Required for search functionality 
plugins:
  - search
  - macros
  - table-reader


# Move custom data to root-level extra
extra:
  productname: images/underconstruction.gif

markdown_extensions:
  - toc:
      permalink: true
      permalink_title: A link to this section you can copy, save, and share.
  - attr_list
  - admonition
  - pymdownx.highlight:
      use_pygments: true
      pygments_lang_class: true
      auto_title: false
      linenums: false
      linenums_style: pymdownx-inline
      anchor_linenums: true
      line_spans: __span
      pygments_style: github-dark
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - codehilite:
      guess_lang: false
      pygments_style: github-dark
  - pymdownx.magiclink # Auto make html hyperlinks into links


nav:
  - Overview: index.md
  - Getting Content: gettingcontent.md
  - Chunking Content: chunkingcontent.md
  - Data Store: datastore.md
  - Use Data: usedata.md
  - Sql notes: sql_cmds.md
  - Unused ideas: unusedideas.md
  - External Links:
      - TBD


